import { saveAs } from 'file-saver';
import React, { useCallback, useState } from 'react';
import API_BASE_URL, { USER_MODULE } from '../../config';
import { useAuth } from '../../hooks/useAuth';
import { SearchResult, SourceReference, SummaryModelConfig } from '../../types/api';
import {
  buildExportFilename,
  exportResultsToDocxBlob,
} from '../../utils/exportResultsToDocx';
import { buildGlobalCitations } from './briefCitations';
import { BriefDocument } from './BriefDocument';
import { BriefHistoryModal } from './BriefHistoryModal';
import { BriefHistoryRail } from './BriefHistoryRail';
import { BriefSeed } from './BriefSeed';
import { useBrief } from './useBrief';
import './brief.css';

const sourceToResult = (src: SourceReference, dataSource: string): SearchResult => ({
  chunk_id: src.chunkId,
  doc_id: src.docId,
  title: src.title,
  document_title: src.title,
  text: src.text,
  page_num: src.page || 1,
  score: src.score,
  headings: src.headings || [],
  data_source: dataSource,
  metadata: {},
});

/**
 * Flatten the brief into one Markdown body + a global SearchResult[] so it can
 * reuse the search summary's .docx exporter. Uses the same global citation
 * model as the on-screen render (combined by document), so `[n]` in the body
 * lines up with the references list and citations link to the source document
 * at the cited page.
 */
// Shown as a call-out box on the exported Word cover so readers treat the
// AI-generated content as a draft to verify, not a finished product.
const BRIEF_DISCLAIMER =
  'This content was auto-generated by AI by deep researching the documents library. ' +
  'Please verify any factual claims closely, and review for coverage and accuracy. ' +
  'This is meant as a guide for humans as part of the writing process, not as a final product.';

const assembleBriefForExport = (
  brief: ReturnType<typeof useBrief>,
  dataSource: string,
): { summary: string; results: SearchResult[] } => {
  const { refs, display } = buildGlobalCitations(brief.sections);
  const lines: string[] = [];
  brief.sections.forEach((s, i) => {
    // The summary section's own H1 is the brief topic; sections sit one level
    // below it. The exporter demotes markdown headings by one, so `#` → H2 and
    // `##` → H3 — keeping sections in the Table of Contents (levels 1–2).
    const hashes = s.level === 2 ? '##' : '#';
    const prefix = brief.numberHeadings ? `${brief.numbers[i]}. ` : '';
    lines.push(`${hashes} ${prefix}${s.title}`, '');
    const d = display.get(s.id);
    if (d?.content) lines.push(d.content, '');
  });
  // refs are ordered by global number, so results[n-1] is the source for `[n]`.
  const results = refs.map((r) => sourceToResult(r.source, dataSource));
  return { summary: lines.join('\n'), results };
};

interface BriefTabProps {
  dataSource: string;
  // The configured chat / deep-research model, used for outline + section research.
  assistantModelConfig?: SummaryModelConfig | null;
  // Opens the document preview (citations/footnotes click through to it).
  onResultClick?: (result: SearchResult) => void;
}

export const BriefTab: React.FC<BriefTabProps> = ({
  dataSource,
  assistantModelConfig,
  onResultClick,
}) => {
  const auth = useAuth();
  // Logged-in users get their own saved-briefs bucket; anonymous users share one.
  const userKey = USER_MODULE && auth.user ? String(auth.user.id) : null;
  const brief = useBrief({ apiBaseUrl: API_BASE_URL, dataSource, assistantModelConfig, userKey });
  const [exportBusy, setExportBusy] = useState(false);

  const handleExportWord = useCallback(async () => {
    if (exportBusy) return;
    setExportBusy(true);
    try {
      const { summary, results } = assembleBriefForExport(brief, dataSource);
      const blob = await exportResultsToDocxBlob({
        query: brief.briefTitle || 'Evidence Brief',
        aiSummary: summary,
        results,
        dataSource,
        documentTitle: 'AI-generated Research Brief',
        summaryHeading: brief.briefTitle || 'Evidence Brief',
        infoBox: BRIEF_DISCLAIMER,
        tableOfContents: true,
        resultsSectionTitle: 'Reference Excerpts',
        siteOrigin:
          typeof window !== 'undefined' && window.location ? window.location.origin : undefined,
      });
      saveAs(blob, buildExportFilename(brief.briefTitle || 'evidence-brief', new Date()));
    } catch (err) {
      brief.setError(err instanceof Error ? err.message : 'Export to Word failed');
    } finally {
      setExportBusy(false);
    }
  }, [exportBusy, brief, dataSource]);

  return (
    <div className="brief-tab">
      {brief.stage === 'seed' ? (
        <BriefSeed brief={brief} />
      ) : (
        <>
          {brief.error && <div className="brief-error brief-error-banner">{brief.error}</div>}
          <div className="brief-builder">
            <BriefHistoryRail brief={brief} />
            <BriefDocument
              brief={brief}
              onResultClick={onResultClick}
              onExportWord={handleExportWord}
              exportBusy={exportBusy}
            />
          </div>
        </>
      )}
      <BriefHistoryModal brief={brief} />
    </div>
  );
};
