import JSZip from 'jszip';
import { Packer } from 'docx';
import { buildExportDocument } from '../utils/exportResultsToDocx';
import type { SearchResult } from '../types/api';

const result = (over: Partial<SearchResult>): SearchResult =>
  ({
    chunk_id: 'c1',
    doc_id: 'd1',
    title: 'Breaking Barriers for Girls Education in Niger',
    text: 'Full excerpt sentence one. Full excerpt sentence two that should appear in italics.',
    score: 0.5,
    page_num: 26,
    headings: [],
    metadata: {},
    ...over,
  }) as SearchResult;

const BRIEF_OPTS = {
  query: 'girls education in Kenya',
  aiSummary: '# 1. Access to schooling\n\nEnrolment has risen [1].\n',
  results: [result({})],
  dataSource: 'wfp',
  documentTitle: 'AI-generated Research Brief',
  summaryHeading: 'girls education in Kenya',
  infoBox: 'This content was auto-generated by AI by deep researching the documents library.',
  tableOfContents: true,
  resultsSectionTitle: 'Reference Excerpts',
  siteOrigin: 'https://example.test',
  now: () => new Date('2026-06-28T20:33:00Z'),
};

const documentXml = async (opts: typeof BRIEF_OPTS): Promise<string> => {
  const buf = await Packer.toBuffer(buildExportDocument(opts));
  const zip = await JSZip.loadAsync(buf);
  return zip.file('word/document.xml')!.async('string');
};

describe('brief Word export', () => {
  test('uses the brief document title, topic heading and disclaimer box', async () => {
    const xml = await documentXml(BRIEF_OPTS);
    expect(xml).toContain('AI-generated Research Brief');
    expect(xml).toContain('girls education in Kenya');
    expect(xml).toContain('auto-generated by AI by deep researching the documents library');
    // No legacy "AI Summary" heading or default cover title.
    expect(xml).not.toContain('AI Summary');
    expect(xml).not.toContain('Evidence Lab — Search Export');
  });

  test('includes a clickable manual TOC (bookmarks, no field, no update prompt)', async () => {
    const xml = await documentXml(BRIEF_OPTS);
    expect(xml).toContain('Contents');
    // TOC entry links internally to a heading bookmark…
    expect(xml).toMatch(/w:anchor="briefheading0"/);
    // …and that bookmark exists on the matching heading.
    expect(xml).toMatch(/<w:bookmarkStart[^>]*w:name="briefheading0"/);
    // No Word TOC field, so Word never prompts to update fields on open.
    expect(xml).not.toMatch(/<w:instrText[^>]*>TOC/);
    const settings = await JSZip.loadAsync(await Packer.toBuffer(buildExportDocument(BRIEF_OPTS)))
      .then((z) => z.file('word/settings.xml')!.async('string'));
    expect(settings).not.toContain('updateFields');
  });

  test('reference excerpt is italicised', async () => {
    const xml = await documentXml(BRIEF_OPTS);
    // The full excerpt sentence renders inside an italic run (<w:i/>).
    const runMatch = xml.match(
      /<w:r>[^]*?Full excerpt sentence two that should appear in italics[^]*?<\/w:r>/,
    );
    expect(runMatch).not.toBeNull();
    expect(runMatch![0]).toContain('<w:i');
  });

  test('reference line shows ", p.N" and an unbolded title', async () => {
    const xml = await documentXml(BRIEF_OPTS);
    expect(xml).toContain(', p.26');
    // Scope to the References list (before the "Reference Excerpts" card section,
    // whose card titles are intentionally bold H3s to match the search export).
    const refSection = xml.split('Reference Excerpts')[0];
    const titleRuns = refSection.match(
      /<w:r>(?:(?!<\/w:r>)[^])*Breaking Barriers for Girls Education in Niger(?:(?!<\/w:r>)[^])*<\/w:r>/g,
    );
    expect(titleRuns).not.toBeNull();
    const anyBoldTitle = titleRuns!.some((r) => /<w:b\b/.test(r));
    expect(anyBoldTitle).toBe(false);
  });
});
