import JSZip from 'jszip';
import { Packer } from 'docx';
import { buildExportDocument } from '../utils/exportResultsToDocx';
import type { SearchResult } from '../types/api';

const TOPIC = 'girls education in Kenya';
const REF_EXCERPTS = 'Reference Excerpts';
const DOC_XML = 'word/document.xml';

const result = (over: Partial<SearchResult>): SearchResult =>
  ({
    chunk_id: 'c1',
    doc_id: 'd1',
    title: 'Breaking Barriers for Girls Education in Niger',
    text: 'Full excerpt sentence one. Full excerpt sentence two that should appear in italics.',
    score: 0.5,
    page_num: 26,
    headings: [],
    metadata: {},
    ...over,
  }) as SearchResult;

const BRIEF_OPTS = {
  query: TOPIC,
  aiSummary: '# 1. Access to schooling\n\nEnrolment has risen [1].\n',
  results: [result({})],
  dataSource: 'wfp',
  documentTitle: 'AI-generated Research Brief',
  summaryHeading: TOPIC,
  infoBox: 'This content was auto-generated by AI by deep researching the documents library.',
  tableOfContents: true,
  resultsSectionTitle: REF_EXCERPTS,
  siteOrigin: 'https://example.test',
  now: () => new Date('2026-06-28T20:33:00Z'),
};

const documentXml = async (opts: typeof BRIEF_OPTS): Promise<string> => {
  const buf = await Packer.toBuffer(buildExportDocument(opts));
  const zip = await JSZip.loadAsync(buf);
  return zip.file(DOC_XML)!.async('string');
};

describe('brief Word export', () => {
  test('uses the brief document title, topic heading and disclaimer box', async () => {
    const xml = await documentXml(BRIEF_OPTS);
    expect(xml).toContain('AI-generated Research Brief');
    expect(xml).toContain(TOPIC);
    expect(xml).toContain('auto-generated by AI by deep researching the documents library');
    // No legacy "AI Summary" heading or default cover title.
    expect(xml).not.toContain('AI Summary');
    expect(xml).not.toContain('Evidence Lab — Search Export');
  });

  test('includes a clickable manual TOC (bookmarks, no field, no update prompt)', async () => {
    const xml = await documentXml(BRIEF_OPTS);
    expect(xml).toContain('Contents');
    // TOC entry links internally to a heading bookmark…
    expect(xml).toMatch(/w:anchor="briefheading0"/);
    // …and that bookmark exists on the matching heading.
    expect(xml).toMatch(/<w:bookmarkStart[^>]*w:name="briefheading0"/);
    // No Word TOC field, so Word never prompts to update fields on open.
    expect(xml).not.toMatch(/<w:instrText[^>]*>TOC/);
    const settings = await JSZip.loadAsync(await Packer.toBuffer(buildExportDocument(BRIEF_OPTS)))
      .then((z) => z.file('word/settings.xml')!.async('string'));
    expect(settings).not.toContain('updateFields');
  });

  test('reference excerpt is a full, italic, smaller-font run inside a bordered box', async () => {
    const xml = await documentXml(BRIEF_OPTS);
    // The full excerpt sentence renders inside an italic, sized-down run…
    const runMatch = xml.match(
      /<w:r>[^]*?Full excerpt sentence two that should appear in italics[^]*?<\/w:r>/,
    );
    expect(runMatch).not.toBeNull();
    expect(runMatch![0]).toContain('<w:i');
    expect(runMatch![0]).toMatch(/<w:sz w:val="18"\/>/); // smaller font (9pt)
    // …and the excerpt's paragraph is a shaded, bordered box.
    const paraMatch = xml.match(
      /<w:p>[^]*?Full excerpt sentence two that should appear in italics[^]*?<\/w:p>/,
    );
    expect(paraMatch![0]).toContain('<w:pBdr>');
    expect(paraMatch![0]).toMatch(/<w:shd[^>]*w:fill="F6F8FA"/);
  });

  test('reference line shows ", p.N" and an unbolded title', async () => {
    const xml = await documentXml(BRIEF_OPTS);
    expect(xml).toContain(', p.26');
    // Scope to the References list (before the "Reference Excerpts" card section,
    // whose card titles are intentionally bold H3s to match the search export).
    const refSection = xml.split(REF_EXCERPTS)[0];
    const titleRuns = refSection.match(
      /<w:r>(?:(?!<\/w:r>)[^])*Breaking Barriers for Girls Education in Niger(?:(?!<\/w:r>)[^])*<\/w:r>/g,
    );
    expect(titleRuns).not.toBeNull();
    const anyBoldTitle = titleRuns!.some((r) => /<w:b\b/.test(r));
    expect(anyBoldTitle).toBe(false);
  });
});

// Hyperlink targets live in the relationships part, not document.xml — read
// them from there to assert where citations point.
const relTargets = async (doc: ReturnType<typeof buildExportDocument>): Promise<string> => {
  const zip = await JSZip.loadAsync(await Packer.toBuffer(doc));
  return zip.file('word/_rels/document.xml.rels')!.async('string');
};

const PDF_URL = 'https://docs.wfp.org/api/documents/WFP-0000169328/download/';

describe('brief Word export — citation links point to the actual document', () => {
  test('citation hyperlink targets the document report_url at the cited page', async () => {
    // The brief maps each source's Report URL into report_url (see BriefTab).
    const opts = { ...BRIEF_OPTS, results: [result({ report_url: PDF_URL })] };
    const rels = await relTargets(buildExportDocument(opts));
    // Openable outside Evidence Lab, jumping straight to the cited page.
    expect(rels).toContain(`${PDF_URL}#page=26`);
    // Falls through to the in-app deep link only when no source URL is present.
    expect(rels).not.toContain('/document/d1');
  });

  test('citation hyperlink also resolves a pdf_url when present', async () => {
    const opts = { ...BRIEF_OPTS, results: [result({ pdf_url: PDF_URL })] };
    const rels = await relTargets(buildExportDocument(opts));
    expect(rels).toContain(`${PDF_URL}#page=26`);
  });

  test('without any source URL, links fall back to the in-app deep link', async () => {
    const rels = await relTargets(buildExportDocument(BRIEF_OPTS));
    expect(rels).toContain('/document/d1');
  });
});

describe('brief Word export — footnote citation style', () => {
  const footOpts = {
    ...BRIEF_OPTS,
    citationStyle: 'footnotes' as const,
    results: [result({ report_url: PDF_URL })],
  };

  const zipOf = async (opts: typeof footOpts) =>
    JSZip.loadAsync(await Packer.toBuffer(buildExportDocument(opts)));

  test('body renders a footnote reference instead of an inline [n] link', async () => {
    const zip = await zipOf(footOpts);
    const xml = await zip.file(DOC_XML)!.async('string');
    expect(xml).toContain('<w:footnoteReference');
    // The prose no longer carries the literal bracketed marker.
    expect(xml).not.toContain('Enrolment has risen [1]');
  });

  test('footnote holds the source title, page and a clickable PDF link', async () => {
    const zip = await zipOf(footOpts);
    const footnotes = await zip.file('word/footnotes.xml')!.async('string');
    expect(footnotes).toContain('Breaking Barriers for Girls Education in Niger');
    expect(footnotes).toContain('p.26');
    expect(footnotes).toContain('Open PDF');
    const rels = await zip.file('word/_rels/footnotes.xml.rels')!.async('string');
    expect(rels).toContain(`${PDF_URL}#page=26`);
  });

  test('footnote mode still includes the reference excerpt section', async () => {
    const zip = await zipOf(footOpts);
    const xml = await zip.file(DOC_XML)!.async('string');
    expect(xml).toContain(REF_EXCERPTS);
  });

  test('multiple citations after one sentence get separated footnote marks', async () => {
    const multiOpts = {
      ...footOpts,
      aiSummary: '# Access\n\nTwo sources agree [1, 2].\n',
      results: [
        result({ chunk_id: 'c1', doc_id: 'd1', report_url: PDF_URL }),
        result({ chunk_id: 'c2', doc_id: 'd2', title: 'Second Source', report_url: PDF_URL }),
      ],
    };
    const zip = await zipOf(multiOpts);
    const xml = await zip.file(DOC_XML)!.async('string');
    // Both citations render as footnote marks…
    const markCount = (xml.match(/<w:footnoteReference\b/g) || []).length;
    expect(markCount).toBe(2);
    // …with a superscript space between them so they read "¹ ²", not "¹²".
    expect(xml).toMatch(
      /<w:footnoteReference[^]*?<w:vertAlign w:val="superscript"\/>[^]*?<w:t xml:space="preserve"> <\/w:t>[^]*?<w:footnoteReference/,
    );
  });

  test('default (links) style emits no footnote references, keeps inline [n]', async () => {
    const zip = await JSZip.loadAsync(await Packer.toBuffer(buildExportDocument(BRIEF_OPTS)));
    const xml = await zip.file(DOC_XML)!.async('string');
    // docx always ships a footnotes part for default separators; the point is
    // that links mode adds no citation footnote *references* to the body…
    expect(xml).not.toContain('<w:footnoteReference');
    // …and keeps the inline bracketed citation marker instead.
    expect(xml).toContain('[');
  });
});
